<?php
/**
 * language.php
 * Centralised localization catalog and helpers.
 */

function get_language_catalog(): array
{
    return [
        'id' => [
            'app_title' => 'Dio\'s Chatbot',
            'new_chat_title' => 'Chat Baru...',
            'send-button' => 'Kirim',
            'file_upload' => 'Unggah Berkas',
            'remove_file' => 'Hapus Berkas',
            'edit_message' => 'Sunting',
            'edit_message_mode' => 'Mode Sunting Pesan',
            'copy_message' => 'Salin',
            'image_upload' => 'Unggahan Gambar',
            'save_btn' => 'Simpan',
            'cancel_btn' => 'Batal',
            'delete_chat' => 'Hapus Chat',
            'delete_chat_confirm' => 'Anda yakin ingin menghapus chat ini?',
            'type_message' => 'Ketik pesan Anda...',
            'new_chat_menu' => 'Mulai Chat Baru',
            'welcome_msg' => 'Selamat Datang',
            'start_chat_prompt' => 'Mulai chat baru dengan mengetik pesan di bawah.',
            'profile_menu' => 'Profil',
            'logout_menu' => 'Keluar',
            'profile_picture_alt' => 'Foto Profil Pengguna',
            'gemini_error' => 'Gagal mendapatkan respons dari Chatbot.',
            'download_file' => 'Lihat Berkas',
            'edit_pending_warning' => 'Pesan ini masih diproses. Tunggu hingga selesai sebelum menyunting.',
            'language_toggle' => 'Bahasa: ID / EN',
            'user_not_found' => 'Pengguna tidak ditemukan.',
            'error_fetch_data' => 'ERROR: Gagal mengambil data.',
            'profile_page_title' => 'Profil Pengguna',
            'profile_account_details_heading' => 'Detail Akun',
            'profile_username_label' => 'Nama Pengguna',
            'profile_email_label' => 'Email',
            'profile_phone_label' => 'Nomor Telepon',
            'profile_joined_label' => 'Bergabung Sejak',
            'profile_edit_profile_button' => 'Edit Profil',
            'profile_change_password_button' => 'Ubah Kata Sandi',
            'edit_profile_title' => 'Edit Profil',
            'edit_profile_info_heading' => 'Informasi Profil',
            'edit_profile_joined_since' => 'Bergabung Sejak',
            'edit_profile_change_photo' => 'Ubah Foto Profil',
            'edit_profile_delete_photo' => 'Hapus Foto Profil Saat Ini',
            'edit_profile_cancel' => 'Batalkan Perubahan',
            'edit_profile_save' => 'Simpan Perubahan',
            'edit_profile_success' => 'Profil berhasil diperbarui!',
            'edit_profile_upload_error' => 'Maaf, terjadi kesalahan saat mengunggah berkas Anda.',
            'edit_profile_invalid_file' => 'Berkas yang diunggah bukan format gambar yang valid.',
            'edit_profile_database_error' => 'ERROR: Terjadi kesalahan database saat memperbarui.',
            'edit_profile_general_error' => 'ERROR:',
            'update_password_title' => 'Ganti Kata Sandi',
            'update_password_heading' => 'Ganti Kata Sandi',
            'update_password_old_label' => 'Kata Sandi Lama',
            'update_password_new_label' => 'Kata Sandi Baru',
            'update_password_confirm_label' => 'Konfirmasi Kata Sandi Baru',
            'update_password_cancel' => 'Batalkan Perubahan',
            'update_password_save' => 'Simpan Perubahan',
            'update_password_success' => 'Kata sandi berhasil diperbarui.',
            'update_password_no_change' => 'Tidak ada perubahan yang dilakukan pada kata sandi.',
            'update_password_error_db_fetch' => 'ERROR Database: Gagal mengambil data pengguna.',
            'update_password_error_db_update' => 'ERROR Database: Gagal memperbarui kata sandi.',
            'update_password_error_old_required' => 'Mohon masukkan kata sandi lama Anda.',
            'update_password_error_old_incorrect' => 'Kata sandi lama salah.',
            'update_password_error_new_required' => 'Mohon masukkan kata sandi baru.',
            'update_password_error_new_length' => 'Kata sandi harus memiliki minimal 6 karakter.',
            'update_password_error_confirm_required' => 'Mohon konfirmasi kata sandi baru.',
            'update_password_error_confirm_mismatch' => 'Konfirmasi kata sandi tidak cocok dengan kata sandi baru.',
            'login_page_title' => 'Login - Dio\'s Chatbot',
            'login_heading' => 'Login Akun',
            'login_email_label' => 'Email',
            'login_password_label' => 'Password',
            'login_submit' => 'Login',
            'login_prompt' => 'Belum punya akun?',
            'login_prompt_link_text' => 'Daftar sekarang',
            'login_error_email_required' => 'Masukkan alamat email.',
            'login_error_password_required' => 'Masukkan password.',
            'login_error_invalid' => 'Email atau password salah.',
            'login_error_query' => 'Terjadi kesalahan saat mengeksekusi query.',
            'login_error_prepare' => 'Gagal mempersiapkan query:',
            'register_page_title' => 'Daftar Akun',
            'register_heading' => 'Daftar Akun',
            'register_subheading' => 'Mohon isi formulir ini untuk membuat akun.',
            'register_username_label' => 'Username',
            'register_email_label' => 'Email',
            'register_password_label' => 'Password',
            'register_phone_label' => 'Nomor Telepon',
            'register_submit' => 'Daftar',
            'register_prompt' => 'Sudah punya akun?',
            'register_prompt_link_text' => 'Login di sini',
            'register_error_username_required' => 'Masukkan username.',
            'register_error_username_taken' => 'Username ini sudah digunakan.',
            'register_error_email_required' => 'Masukkan email.',
            'register_error_email_invalid' => 'Format email tidak valid.',
            'register_error_email_taken' => 'Email ini sudah digunakan.',
            'register_error_password_required' => 'Masukkan password.',
            'register_error_password_length' => 'Password minimal 6 karakter.',
            'register_error_phone_required' => 'Masukkan nomor telepon.',
            'register_error_database' => 'Ups! Terjadi kesalahan. Silakan coba lagi nanti.',
        ],
        'en' => [
            'app_title' => 'Dio\'s Chatbot',
            'new_chat_title' => 'New Chat...',
            'send-button' => 'Send',
            'file_upload' => 'Upload File',
            'remove_file' => 'Remove File',
            'edit_message' => 'Edit',
            'edit_message_mode' => 'Edit Message Mode',
            'copy_message' => 'Copy',
            'image_upload' => 'Image Upload',
            'save_btn' => 'Save',
            'cancel_btn' => 'Cancel',
            'delete_chat' => 'Delete Chat',
            'delete_chat_confirm' => 'Are you sure you want to delete this chat?',
            'type_message' => 'Type your message...',
            'new_chat_menu' => 'Start New Chat',
            'welcome_msg' => 'Welcome',
            'start_chat_prompt' => 'Start a new chat by typing your message below.',
            'profile_menu' => 'Profile',
            'logout_menu' => 'Logout',
            'profile_picture_alt' => 'User Profile Picture',
            'gemini_error' => 'Failed to get response from Chatbot.',
            'download_file' => 'View File',
            'edit_pending_warning' => 'This message is still processing. Please wait before editing.',
            'language_toggle' => 'Language: EN / ID',
            'user_not_found' => 'User not found.',
            'error_fetch_data' => 'ERROR: Failed to fetch data.',
            'profile_page_title' => 'User Profile',
            'profile_account_details_heading' => 'Account Details',
            'profile_username_label' => 'Username',
            'profile_email_label' => 'Email',
            'profile_phone_label' => 'Phone Number',
            'profile_joined_label' => 'Member Since',
            'profile_edit_profile_button' => 'Edit Profile',
            'profile_change_password_button' => 'Change Password',
            'edit_profile_title' => 'Edit Profile',
            'edit_profile_info_heading' => 'Profile Information',
            'edit_profile_joined_since' => 'Member Since',
            'edit_profile_change_photo' => 'Change Profile Photo',
            'edit_profile_delete_photo' => 'Remove Current Profile Photo',
            'edit_profile_cancel' => 'Cancel Changes',
            'edit_profile_save' => 'Save Changes',
            'edit_profile_success' => 'Profile updated successfully!',
            'edit_profile_upload_error' => 'Sorry, something went wrong while uploading your file.',
            'edit_profile_invalid_file' => 'The uploaded file is not a valid image format.',
            'edit_profile_database_error' => 'ERROR: A database error occurred while updating.',
            'edit_profile_general_error' => 'ERROR:',
            'update_password_title' => 'Change Password',
            'update_password_heading' => 'Change Password',
            'update_password_old_label' => 'Current Password',
            'update_password_new_label' => 'New Password',
            'update_password_confirm_label' => 'Confirm New Password',
            'update_password_cancel' => 'Cancel Changes',
            'update_password_save' => 'Save Changes',
            'update_password_success' => 'Password updated successfully.',
            'update_password_no_change' => 'No changes were made to the password.',
            'update_password_error_db_fetch' => 'Database ERROR: Failed to fetch user data.',
            'update_password_error_db_update' => 'Database ERROR: Failed to update the password.',
            'update_password_error_old_required' => 'Please enter your current password.',
            'update_password_error_old_incorrect' => 'The current password is incorrect.',
            'update_password_error_new_required' => 'Please enter a new password.',
            'update_password_error_new_length' => 'The password must be at least 6 characters.',
            'update_password_error_confirm_required' => 'Please confirm your new password.',
            'update_password_error_confirm_mismatch' => 'The confirmation password does not match the new password.',
            'login_page_title' => 'Login - Dio\'s Chatbot',
            'login_heading' => 'Sign In',
            'login_email_label' => 'Email',
            'login_password_label' => 'Password',
            'login_submit' => 'Login',
            'login_prompt' => 'Don\'t have an account?',
            'login_prompt_link_text' => 'Register now',
            'login_error_email_required' => 'Please enter your email address.',
            'login_error_password_required' => 'Please enter your password.',
            'login_error_invalid' => 'Incorrect email or password.',
            'login_error_query' => 'An error occurred while executing the query.',
            'login_error_prepare' => 'Failed to prepare the query:',
            'register_page_title' => 'Create Account',
            'register_heading' => 'Create Account',
            'register_subheading' => 'Please fill out this form to create an account.',
            'register_username_label' => 'Username',
            'register_email_label' => 'Email',
            'register_password_label' => 'Password',
            'register_phone_label' => 'Phone Number',
            'register_submit' => 'Register',
            'register_prompt' => 'Already have an account?',
            'register_prompt_link_text' => 'Login here',
            'register_error_username_required' => 'Please enter a username.',
            'register_error_username_taken' => 'This username is already taken.',
            'register_error_email_required' => 'Please enter an email.',
            'register_error_email_invalid' => 'The email format is invalid.',
            'register_error_email_taken' => 'This email is already in use.',
            'register_error_password_required' => 'Please enter a password.',
            'register_error_password_length' => 'The password must be at least 6 characters.',
            'register_error_phone_required' => 'Please enter a phone number.',
            'register_error_database' => 'Oops! Something went wrong. Please try again later.',
        ],
    ];
}

function get_supported_languages(): array
{
    return array_keys(get_language_catalog());
}

function get_texts(string $lang): array
{
    $catalog = get_language_catalog();
    return $catalog[$lang] ?? $catalog['id'];
}
